### ISSUE TITLE
Internal server issue

### ISSUE THREAD

**Issue by ahdee** [bhklab/PharmacoDB#143]
Hi I notice that for some cell line there is an internal server issue, for example I search for hs737 and click on the link but go an error message instead. 
 
https://pharmacodb.pmgenomics.ca/cell_lines/Hs737.T_591_2019

Is this an error or is there just no data for this cell line. 
thanks!

**Comment by gangeshberi** [comment]
We will investigate this and see what exactly is going on, but it seems like a bug. Thanks for opening an Issue! I see this behaviour with almost all the cell lines starting with Hs.

**Comment by chuntul** [comment]
It's because there's a period in the cell line name, which screws up the URL. We have to parse these and other special characters out of the cell lines.

**Comment by gangeshberi** [comment]
@chuntul That's true, it's messing because of the period, I will fix this shortly! That's what it looks like, but let's investigate what exactly is the issue.

**Comment by gangeshberi** [comment]
@ahdee  It has been resolved! Let me know if you find any issues.
