### ISSUE TITLE
is the server up?

### ISSUE THREAD

**Issue by vjcitn** [bhklab/PharmacoDB#33]
https://api.pharmacodb.com/v1/cell_lines fails

**Comment by kofiav** [comment]
Hi Vince, 

The API is up at https://pharmacodb.pmgenomics.ca/api/v1/cell_lines. We are trying to set up a CNAME at api.pharmacodb.com so that users can be routed to this new location. Sorry for any inconvenience.

**Comment by vjcitn** [comment]
hi -- i am getting a bad gateway at

https://pharmacodb.pmgenomics.ca/api/v1/


any major changes to API?

**Comment by kofiav** [comment]
Hi Vince, 

We are currently making some changes to our backend architecture. The issue will be resolved by the end of today.

**Comment by kofiav** [comment]
Issue should be resolved.
