### ISSUE TITLE
Labels are slightly cut in the Venn Diagram

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB#8]
See CTRPv2 label in http://pharmacodb.pmgenomics.ca/search?q=ctrpv2+gdsc1000+gcsi

**Comment by kofiav** [comment]
Are you using Chrome? 
I can't reproduce the issue in the most up to date version of PharmacoDB

**Comment by kofiav** [comment]
See: http://opennet-33-51.uhnres.utoronto.ca:3001/search?q=ctrpv2+gdsc1000+gcsi

**Comment by kofiav** [comment]
Issue has been fixed as of latest deployment.
