### ISSUE TITLE
Problem with dataset overlap

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB#80]
The overlap of compounds increase with increasing number of datasets, which does not make ANY sense

![screen shot 2018-11-11 at 21 55 19](https://user-images.githubusercontent.com/594954/48323927-8757d600-e5fc-11e8-94ce-f4e5f57d5d78.png)
![screen shot 2018-11-11 at 21 59 11](https://user-images.githubusercontent.com/594954/48324037-28469100-e5fd-11e8-8386-4795cb33d126.png)

**Comment by chuntul** [comment]
fixed with the newest commit https://github.com/bhklab/PharmacoDB-web/commit/523ccadbc6015d61c4687eb6f701376474693c75

**Comment by bhaibeka** [comment]
http://beta.pharmacodb.ca/search?q=GDSC1000+CTRPv2+GRAY+gCSI

How can the overlap between all datasets be 20 while gCSI contains only 16 drugs?
