### ISSUE TITLE
API endpoint links do not resolve as intended

### ISSUE THREAD

**Issue by vjcitn** [bhklab/PharmacoDB#9]
README.md says "Visit each endpoint link above to see a list of all the options that are available to that endpoint."

link for /cell_lines is https://github.com/bhklab/PharmacoDB/blob/master/doc/template.md

**Comment by kofiav** [comment]
@vjcitn thanks for notifying us, we are currently taking care of it. Let us know if you've got any other questions!

**Comment by assefamaru** [comment]
@vjcitn api docs have now been updated, and include parameter options for each endpoint. Readme links for each endpoint should now resolve to their corresponding doc page. Feel free to open a new issue if you find anything unclear in the documentation, or in case of any errors!

**Comment by vjcitn** [comment]
Thanks for the quick solution!
